name: 🐧 Linux Builds
on:
  workflow_call:
    inputs:
      changed-files:
        description: A list of changed files, pre-filtered for parsing by clangd-tidy.
        required: true
        type: string
  workflow_dispatch:

# Global Settings
env:
  SCONS_FLAGS: >-
    dev_mode=yes
    module_text_server_fb_enabled=yes
  GODOT_CPP_BRANCH: 4.5
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  ASAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/asan.txt
  LSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/lsan.txt
  TSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/tsan.txt
  UBSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/ubsan.txt

jobs:
  build-linux:
    # Stay one LTS before latest to increase portability of Linux artifacts.
    runs-on: ubuntu-22.04
    name: ${{ matrix.name }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Minimal template (target=template_release, everything disabled)
            cache-name: linux-template-minimal
            target: template_release
            scons-flags: >-
              dev_mode=no
              debug_symbols=no
              modules_enabled_by_default=no
              module_freetype_enabled=yes
              module_gdscript_enabled=yes
              module_jpg_enabled=yes
              module_regex_enabled=yes
              module_svg_enabled=yes
              module_text_server_adv_enabled=yes
              module_zip_enabled=yes
              module_webp_enabled=yes
              disable_3d=yes
              disable_advanced_gui=no
              disable_navigation_2d=yes
              disable_navigation_3d=yes
              disable_physics_2d=yes
              disable_physics_3d=yes
              disable_xr=yes
              deprecated=no
              brotli=no
              optimize=size_extra
              lto=full
              x11=yes
              accesskit=no
            bin: ./bin/godot.app_template.x86_64
            artifact: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-bin  # TODO: Figure out somehow how to embed this one.
          if [ "${{ matrix.proj-test }}" == "true" -o "${{ matrix.proj-export }}" == "true" ]; then
            sudo apt-get install mesa-vulkan-drivers
          fi

      - name: Free disk space on runner
        if: matrix.free-space
        run: |
          echo "Disk usage before:" && df -h
          sudo rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        if: "!matrix.legacy-scons"
        uses: ./.github/actions/godot-deps

      - name: Setup Python and SCons (legacy versions)
        if: matrix.legacy-scons
        uses: ./.github/actions/godot-deps
        with:
          # Sync with Ensure*Version in SConstruct.
          python-version: 3.9
          scons-version: 4.4

      - name: Force remove preinstalled .NET SDKs
        if: matrix.build-mono
        run: |
          sudo rm -rf /usr/share/dotnet/sdk/*

      - name: Setup older .NET SDK as baseline
        if: matrix.build-mono
        uses: actions/setup-dotnet@v5
        with:
          # Targeting the oldest version we want to support to ensure it still builds.
          dotnet-version: 8.0.100

      - name: Download pre-built AccessKit
        shell: sh
        id: accesskit-sdk
        run: |
          if python ./misc/scripts/install_accesskit.py; then
            echo "ACCESSKIT_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::AccessKit SDK installation failed, building without AccessKit support."
            echo "ACCESSKIT_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Install mold linker
        if: matrix.proj-test
        uses: rui314/setup-mold@v1

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Style checks via clangd-tidy
        if: matrix.clangd-tidy
        uses: ./.github/actions/clangd-tidy
        with:
          changed-files: ${{ inputs.changed-files }}

      - name: Compilation (godot-cpp)
        uses: ./.github/actions/godot-cpp-build
        if: matrix.godot-cpp
        with:
          bin: ${{ matrix.bin }}
          scons-flags: verbose=yes
          godot-cpp-branch: ${{ env.GODOT_CPP_BRANCH }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        if: matrix.artifact
        run: |
          rm -rf ./bin/build_deps
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: matrix.artifact
        with:
          name: ${{ matrix.cache-name }}
